version: '3'

services:
  proxy-pool:
    build: .
    container_name: proxy-pool
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/stats"]
      interval: 1m
      timeout: 10s
      retries: 3 